export default {
  // application actions
  LOADING: "LOADING",
  LOADED: "LOADED",

  // auth actions
  LOGGED_IN: "LOGGED_IN",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTERED: "REGISTERED",
  REGISTER_FAILED: "REGISTER_FAILED",
  USER_LOADED: "USER_LOADED",
  USER_LOAD_FAILED: "USER_LOAD_FAILED",
  LOGGED_OUT: "LOGGED_OUT",
};
